import { expect, test } from "@playwright/test";
import { execFile } from "node:child_process";
import { readFile } from "node:fs/promises";
import Database from "better-sqlite3";
import path from "node:path";
import { promisify } from "node:util";

const execFileAsync = promisify(execFile);

test("director can set up, import, check out, return with damage, back up, and sign out", async ({ page, request }) => {
  test.setTimeout(180_000);
  const health = await request.get("/api/health");
  expect(health.status()).toBe(200);
  expect(await health.json()).toEqual({ status: "ok" });
  await page.goto("/today");
  await expect(page).toHaveURL(/\/login/);
  await expect(page.getByRole("heading", { name: "Create the director account" })).toBeVisible();
  await expect(page.getByText("Alpha data boundary")).toBeVisible();
  await expect(page.getByText(/Evaluate with fictional data first/)).toBeVisible();
  await page.getByRole("link", { name: "Fictional demo" }).click();
  await expect(page.getByRole("heading", { name: "Explore the fictional demo" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Load fictional demo" })).toBeVisible();
  await page.getByRole("link", { name: "My program" }).click();
  await page.getByLabel("Program name").fill("Ridgeline Middle School Band");
  await page.getByLabel("Username").fill("director-e2e");
  await page.getByLabel("Password", { exact: true }).fill("BandOffice-E2E-Password!");
  await page.getByLabel("Confirm password").fill("BandOffice-E2E-Password!");
  await page.getByRole("button", { name: "Create account" }).click();
  await expect(page).toHaveURL(/\/today/);

  await page.goto("/import");
  const csvInput = page.getByLabel("Select students CSV");
  await expect(csvInput).toBeEnabled();
  await csvInput.setInputFiles(path.resolve("tests/fixtures/import-members.csv"));
  await expect(page.getByText("1 rows ready for reconciliation")).toBeVisible();
  await page.getByRole("button", { name: "Import students" }).click();
  await expect(page.getByText("Roster import complete: 1 created, 0 updated.")).toBeVisible();

  await page.goto("/groups");
  const clarinetGroup = page.getByRole("link", { name: /clarinet/i });
  await expect(clarinetGroup).toBeVisible();
  await page.screenshot({ path: "test-results/e2e-groups-desktop.png", fullPage: true });
  await clarinetGroup.click();
  await expect(page.getByText("Verifier, Release", { exact: true })).toBeVisible();
  const groupLayout = await page.evaluate(() => ({ scrollX: window.scrollX, scrollWidth: document.documentElement.scrollWidth, viewportWidth: window.innerWidth }));
  expect(groupLayout.scrollX).toBe(0);
  expect(groupLayout.scrollWidth).toBeLessThanOrEqual(groupLayout.viewportWidth);
  await page.screenshot({ path: "test-results/e2e-group-detail-desktop.png", fullPage: true });
  await page.goto("/roster");
  await expect(page.getByRole("heading", { name: "People" })).toBeVisible();
  await page.screenshot({ path: "test-results/e2e-people-desktop.png", fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: "test-results/e2e-people-mobile.png", fullPage: true });
  await page.setViewportSize({ width: 1280, height: 720 });

  await page.goto("/roster");
  await page.locator("summary").filter({ hasText: "Add person" }).click();
  const contactForm = page.locator("form").filter({ hasText: "New person" });
  await contactForm.locator('input[name="firstName"]').fill("Avery");
  await contactForm.locator('input[name="lastName"]').fill("Supporter");
  await contactForm.locator('input[name="email"]').fill("avery.supporter@example.test");
  await contactForm.locator('input[name="classifications"][value="STUDENT"]').uncheck();
  await contactForm.locator('input[name="classifications"][value="BOOSTER"]').check();
  await contactForm.getByRole("button", { name: "Add person" }).click();
  await expect(page.getByText("Person added to the directory.")).toBeVisible();

  await page.locator("summary").filter({ hasText: "Add person" }).click();
  const unrelatedStudentForm = page.locator("form").filter({ hasText: "New person" });
  await unrelatedStudentForm.locator('input[name="firstName"]').fill("Morgan");
  await unrelatedStudentForm.locator('input[name="lastName"]').fill("Other");
  await unrelatedStudentForm.locator('input[name="email"]').fill("morgan.other@example.test");
  await unrelatedStudentForm.locator('input[name="grade"]').fill("8");
  await unrelatedStudentForm.getByRole("button", { name: "Add person" }).click();
  await expect(page.getByText("Person added to the directory.")).toBeVisible();

  await page.goto("/communications/settings");
  await page.getByLabel("Sender name").fill("Ridgeline Band");
  await page.getByLabel("From address").fill("band@ridgeline.example");
  await page.getByLabel("SMTP host").fill("smtp.ridgeline.example");
  await page.getByLabel("SMTP port").fill("587");
  await page.getByRole("button", { name: "Save connection" }).click();
  await expect(page.getByText(/Shared mailbox settings saved/)).toBeVisible();
  await page.getByRole("button", { name: "Verify connection" }).click();
  await expect(page.getByText(/Connection verified/)).toBeVisible();

  const e2eDatabase = new Database(path.resolve("data/e2e.db"));
  const avery = e2eDatabase.prepare(`SELECT "id" FROM "Person" WHERE "email" = ?`).get("avery.supporter@example.test") as { id: string };
  const verifier = e2eDatabase.prepare(`SELECT "id" FROM "Person" WHERE "firstName" = ? AND "lastName" = ?`).get("Release", "Verifier") as { id: string };
  e2eDatabase.close();
  await page.goto(`/roster/${verifier.id}`);
  await page.getByLabel("Guardian", { exact: true }).fill("Avery Supporter");
  await page.getByRole("option", { name: /Supporter, Avery/ }).click();
  await page.getByLabel("Relationship").fill("Parent");
  await page.getByLabel("Primary contact").check();
  await page.getByRole("button", { name: "Save relationship" }).click();
  await expect(page.getByText("Guardian relationship saved.")).toBeVisible();
  await expect(page.getByText("Avery Supporter", { exact: true })).toBeVisible();
  await page.screenshot({ path: "test-results/e2e-family-links-desktop.png", fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: "test-results/e2e-family-links-mobile.png", fullPage: true });
  await page.setViewportSize({ width: 1280, height: 720 });
  await page.goto(`/roster/${avery.id}`);
  await page.getByRole("button", { name: "Enable portal access" }).click();
  await expect(page.getByText(/Portal access enabled/)).toBeVisible();
  await expect(page.getByText("PENDING")).toBeVisible();
  await page.getByRole("button", { name: "Sign out" }).click();

  await page.goto("/portal/login");
  await page.getByRole("link", { name: "Forgot or need to set your password?" }).click();
  await page.waitForLoadState("networkidle");
  await page.getByLabel("Email").fill("avery.supporter@example.test");
  await page.getByRole("button", { name: "Email reset code" }).click();
  await expect(page.getByText(/If an eligible portal account uses that email/)).toBeVisible();
  await page.getByRole("link", { name: "I already have a code" }).click();
  await page.waitForLoadState("networkidle");
  await page.getByLabel("8-digit code").fill("24681357");
  await page.getByLabel("New password").fill("BandOffice-Guardian-E2E-Password!");
  await page.getByLabel("Confirm password").fill("BandOffice-Guardian-E2E-Password!");
  await page.getByLabel("Email").fill("avery.supporter@example.test");
  await page.getByRole("button", { name: "Update password" }).click();
  await expect(page.getByText("Password updated. You can sign in now.")).toBeVisible();
  await page.waitForLoadState("networkidle");
  await page.getByLabel("Password").fill("BandOffice-Guardian-E2E-Password!");
  await page.getByLabel("Email").fill("avery.supporter@example.test");
  await page.getByRole("button", { name: "Sign in" }).click();
  await expect(page).toHaveURL(/\/portal$/);
  await expect(page.getByRole("heading", { name: "Program account" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Release Verifier" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Morgan Other" })).toHaveCount(0);
  await expect(page.getByText("No property is currently assigned.")).toBeVisible();
  await page.screenshot({ path: "test-results/e2e-guardian-portal-desktop.png", fullPage: true });
  await page.getByRole("button", { name: "Sign out" }).click();

  await page.goto("/login");
  await page.getByLabel("Username").fill("director-e2e");
  await page.getByLabel("Password").fill("BandOffice-E2E-Password!");
  await page.getByRole("button", { name: "Sign in" }).click();
  await expect(page).toHaveURL(/\/today/);

  await page.goto(`/roster/${verifier.id}`);
  await page.locator("summary").filter({ hasText: "Edit person" }).click();
  const studentEditForm = page.locator("form").filter({ hasText: "Edit person" });
  await studentEditForm.locator('input[name="email"]').fill("release.verifier@example.test");
  await studentEditForm.getByRole("button", { name: "Save changes" }).click();
  await expect(page.getByRole("status")).toContainText("Person record updated.");
  await expect(page.getByText("release.verifier@example.test", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Enable portal access" }).click();
  await expect(page.getByText(/Portal access enabled/)).toBeVisible();
  await page.getByRole("button", { name: "Sign out" }).click();

  await page.goto("/portal/forgot-password");
  await page.getByLabel("Email").fill("release.verifier@example.test");
  await page.getByRole("button", { name: "Email reset code" }).click();
  await expect(page.getByText(/If an eligible portal account uses that email/)).toBeVisible();
  await page.getByRole("link", { name: "I already have a code" }).click();
  await page.waitForLoadState("networkidle");
  await page.getByLabel("8-digit code").fill("24681357");
  await page.getByLabel("New password").fill("BandOffice-Student-E2E-Password!");
  await page.getByLabel("Confirm password").fill("BandOffice-Student-E2E-Password!");
  await page.getByLabel("Email").fill("release.verifier@example.test");
  await page.getByRole("button", { name: "Update password" }).click();
  await expect(page.getByText("Password updated. You can sign in now.")).toBeVisible();
  await page.getByLabel("Email").fill("release.verifier@example.test");
  await page.getByLabel("Password").fill("BandOffice-Student-E2E-Password!");
  await page.getByRole("button", { name: "Sign in" }).click();
  await expect(page).toHaveURL(/\/portal$/);
  await expect(page.getByRole("heading", { name: "Release Verifier" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Morgan Other" })).toHaveCount(0);
  await page.screenshot({ path: "test-results/e2e-student-portal-desktop.png", fullPage: true });
  await page.getByRole("button", { name: "Sign out" }).click();

  await page.goto("/login");
  await page.getByLabel("Username").fill("director-e2e");
  await page.getByLabel("Password").fill("BandOffice-E2E-Password!");
  await page.getByRole("button", { name: "Sign in" }).click();
  await expect(page).toHaveURL(/\/today/);

  await page.goto("/communications/new");
  await page.getByLabel("Subject").fill("E2E booster announcement");
  await page.getByLabel("Message").fill("This is a deterministic communication workflow test.");
  await page.locator('input[name="classificationTargets"][value="BOOSTER"]').check();
  await page.getByRole("button", { name: "Build audience preview" }).click();
  await expect(page.getByText("Audience snapshot created. Review every recipient before sending.")).toBeVisible();
  await expect(page.getByText("avery.supporter@example.test")).toBeVisible();
  await page.screenshot({ path: "test-results/e2e-communications-preview-desktop.png", fullPage: true });
  await page.getByRole("link", { name: "Edit" }).click();
  await page.getByLabel("Subject").fill("Updated E2E booster announcement");
  await page.getByRole("button", { name: "Save and rebuild preview" }).click();
  await expect(page.getByText("Announcement and audience snapshot updated.")).toBeVisible();
  await expect(page.getByRole("heading", { name: "Updated E2E booster announcement" })).toBeVisible();
  await page.getByRole("button", { name: "Send to 1" }).click();
  await expect(page.getByText("1 messages accepted by the email provider.")).toBeVisible();
  await expect(page.getByText("sent", { exact: true }).first()).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("/communications");
  await expect(page.getByRole("heading", { name: "Email communications" })).toBeVisible();
  await page.screenshot({ path: "test-results/e2e-communications-mobile.png", fullPage: true });
  await page.setViewportSize({ width: 1280, height: 720 });

  await page.goto("/financials");
  await expect(page.getByRole("heading", { name: "Financials" })).toBeVisible();
  await page.locator("summary").filter({ hasText: "Assess group" }).click();
  const assessmentForm = page.locator("form").filter({ hasText: "Post group assessment" });
  await assessmentForm.locator('select[name="groupId"]').selectOption({ label: "clarinet · 1 students" });
  await assessmentForm.locator('input[name="description"]').fill("E2E program fee");
  await assessmentForm.locator('input[name="amount"]').fill("25.00");
  await assessmentForm.getByRole("button", { name: "Post assessment" }).click();
  await expect(page.getByText("Assessment posted to 1 student accounts.")).toBeVisible();
  await expect(page.getByText("$25.00", { exact: true }).first()).toBeVisible();
  await page.getByRole("row", { name: /Verifier, Release/ }).getByRole("link", { name: "Statement" }).click();
  await expect(page.getByRole("heading", { name: "Release Verifier" })).toBeVisible();
  await page.locator("summary").filter({ hasText: "Post entry" }).click();
  const entryForm = page.locator("form").filter({ hasText: "Post account entry" });
  await entryForm.locator('select[name="type"]').selectOption("PAYMENT");
  await entryForm.locator('input[name="amount"]').fill("10.00");
  await entryForm.locator('input[name="description"]').fill("Manual payment received");
  await entryForm.locator('input[name="reference"]').fill("E2E-RECEIPT-1");
  await entryForm.getByRole("button", { name: "Post entry" }).click();
  await expect(page.getByText("Financial entry posted.")).toBeVisible();
  await expect(page.getByText("$15.00", { exact: true }).first()).toBeVisible();
  await page.getByLabel("Reverse Manual payment received").click();
  const reversalForm = page.locator("details[open] form.reversal-form");
  await reversalForm.locator('input[name="reason"]').fill("E2E correction");
  await reversalForm.getByRole("button", { name: "Post reversal" }).click();
  await expect(page.getByText("Ledger entry reversed. The original remains in the statement.")).toBeVisible();
  await expect(page.getByText("$25.00", { exact: true }).first()).toBeVisible();
  await page.screenshot({ path: "test-results/e2e-financial-statement-desktop.png", fullPage: true });
  const statementDownloadPromise = page.waitForEvent("download");
  await page.getByRole("link", { name: "CSV" }).click();
  const statementDownload = await statementDownloadPromise;
  expect(statementDownload.suggestedFilename()).toBe("band-office-financial-statement.csv");
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("/financials");
  await expect(page.locator(".mobile-nav").getByRole("link", { name: "Financials" })).toBeVisible();
  await page.screenshot({ path: "test-results/e2e-financials-mobile.png", fullPage: true });
  await page.setViewportSize({ width: 1280, height: 720 });

  await page.goto("/library");
  await expect(page.getByRole("heading", { name: "Music library" })).toBeVisible();
  await page.locator("summary").filter({ hasText: "Add music" }).click();
  const libraryForm = page.locator("form").filter({ hasText: "New whole-set record" });
  await libraryForm.getByLabel("Title").fill("E2E Concert Work");
  await libraryForm.getByLabel("Composer").fill("Release Composer");
  await libraryForm.getByLabel("Grade").fill("2.5");
  await libraryForm.getByLabel("Category").fill("Concert band");
  await libraryForm.getByLabel("Catalog number").fill("E2E-LIB-001");
  await libraryForm.getByLabel("Storage location").fill("Shelf E2E-1");
  await libraryForm.getByRole("button", { name: "Add to library" }).click();
  await expect(page.getByText("Music set added to the library.")).toBeVisible();
  await expect(page.getByRole("heading", { name: "E2E Concert Work" })).toBeVisible();

  await page.locator("summary").filter({ hasText: "Add issue" }).click();
  const componentForm = page.locator("form").filter({ hasText: "Record component issue" });
  await componentForm.getByLabel("Component").fill("Clarinet 2 part");
  await componentForm.getByRole("button", { name: "Add issue" }).click();
  await expect(page.getByText("Component issue recorded.")).toBeVisible();
  await expect(page.getByText("Set incomplete")).toBeVisible();
  await page.getByRole("button", { name: "Mark replaced" }).click();
  await expect(page.getByText("Component marked replaced and resolved.")).toBeVisible();

  await page.getByRole("textbox", { name: "External borrower", exact: true }).fill("E2E Neighbor School");
  await page.getByLabel("Expected return").fill("2026-08-15");
  await page.getByRole("button", { name: "Check out set" }).click();
  await expect(page.getByText("Complete score-and-parts set checked out.")).toBeVisible();
  await expect(page.getByText("E2E Neighbor School", { exact: true }).first()).toBeVisible();
  await page.locator("summary").filter({ hasText: "Close loan" }).click();
  const closeLoanForm = page.locator("form").filter({ hasText: "Close whole-set loan" });
  await closeLoanForm.getByRole("button", { name: "Close loan" }).click();
  await expect(page.getByText("Library loan closed.")).toBeVisible();

  await page.locator("summary").filter({ hasText: "Add performance" }).click();
  const performanceForm = page.locator("form").filter({ hasText: "Add performance" });
  await performanceForm.getByLabel("Performance or event").fill("E2E Spring Concert");
  await performanceForm.getByLabel("Group").selectOption({ label: "clarinet" });
  await performanceForm.getByLabel("Conductor").fill("Release Director");
  await performanceForm.getByRole("button", { name: "Add performance" }).click();
  await expect(page.getByText("Performance added to the set history.")).toBeVisible();

  await page.locator("summary").filter({ hasText: "Add link" }).click();
  const linkForm = page.locator("form").filter({ hasText: "Add external resource" });
  await linkForm.getByLabel("Label").fill("Publisher reference");
  await linkForm.getByLabel("HTTPS link").fill("https://example.invalid/e2e-library");
  await linkForm.getByRole("checkbox").check();
  await linkForm.getByRole("button", { name: "Add link" }).click();
  await expect(page.getByText("External resource link added.")).toBeVisible();

  await page.locator("summary").filter({ hasText: "Upload" }).click();
  const uploadForm = page.locator("form").filter({ hasText: "Store local file" });
  await uploadForm.getByLabel("Label").fill("E2E resource file");
  await uploadForm.locator('input[type="file"]').setInputFiles(path.resolve("tests/fixtures/library-resource.txt"));
  await uploadForm.getByRole("checkbox").check();
  await uploadForm.getByRole("button", { name: "Store file" }).click();
  await expect(page.getByText("Local file stored in the managed Band Office library.")).toBeVisible();
  const resourceDownloadPromise = page.waitForEvent("download");
  await page.getByRole("link", { name: "Download" }).click();
  expect((await resourceDownloadPromise).suggestedFilename()).toBe("library-resource.txt");
  await page.screenshot({ path: "test-results/e2e-library-detail-desktop.png", fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("/library");
  await expect(page.locator(".mobile-nav").getByRole("link", { name: "Library" })).toBeVisible();
  await page.screenshot({ path: "test-results/e2e-library-mobile.png", fullPage: true });
  await page.setViewportSize({ width: 1280, height: 720 });
  const libraryExport = await page.evaluate(async () => {
    const response = await fetch("/api/export/library-catalog");
    return { status: response.status, text: await response.text() };
  });
  expect(libraryExport.status).toBe(200);
  expect(libraryExport.text).toContain("E2E Concert Work");

  await page.goto("/forms");
  await expect(page.getByRole("heading", { name: "Forms" })).toBeVisible();
  await page.locator("summary").filter({ hasText: "New template" }).click();
  const templateForm = page.locator("form").filter({ hasText: "Create form template" });
  await templateForm.getByLabel("Template name").fill("E2E travel response");
  await templateForm.getByLabel("Form title").fill("E2E travel response");
  await templateForm.getByLabel("Instructions").fill("Complete this deterministic release form.");
  await templateForm.getByLabel("Retention days").fill("30");
  await templateForm.getByRole("button", { name: "Create draft" }).click();
  await expect(page.getByText("Draft form created. Add questions before publishing.")).toBeVisible();

  const addQuestion = async (prompt: string, type: string, options = "", required = false) => {
    await page.locator("summary").filter({ hasText: "Add question" }).click();
    const questionForm = page.locator("form").filter({ hasText: "Add question" });
    await questionForm.getByLabel("Prompt").fill(prompt);
    await questionForm.getByLabel("Type").selectOption(type);
    if (options) await questionForm.getByLabel("Choice options").fill(options);
    if (required) await questionForm.getByLabel("Response required before completion").check();
    await questionForm.getByRole("button", { name: "Add question" }).click();
    await expect(page.locator(".form-question-card").getByText(prompt, { exact: true })).toBeVisible();
  };
  await addQuestion("Pickup contact name", "SHORT_TEXT", "", true);
  await addQuestion("Transportation plan", "SINGLE_CHOICE", "School bus\nApproved family pickup", true);
  await addQuestion("I acknowledge the itinerary may change.", "ACKNOWLEDGMENT");
  await addQuestion("Optional approved document", "FILE_UPLOAD");
  await page.getByRole("button", { name: "Publish form" }).click();
  await expect(page.getByText("Form version published and locked for use.")).toBeVisible();
  await page.locator("summary").filter({ hasText: "Create request campaign" }).click();
  const campaignForm = page.locator("form").filter({ hasText: "Assign E2E travel response" });
  await campaignForm.getByLabel("Campaign name").fill("E2E fall travel forms");
  await campaignForm.getByLabel("Recipients").selectOption("STUDENTS");
  await campaignForm.getByLabel("Audience source").selectOption("GROUP");
  await campaignForm.locator('select[name="groupId"]').selectOption({ label: "clarinet" });
  await campaignForm.getByRole("button", { name: "Create recipient requests" }).click();
  await expect(page.getByText("Recipient requests created from the current People and Groups records.")).toBeVisible();
  const campaignUrl = page.url();
  await page.getByRole("button", { name: "Draft reminder" }).click();
  await expect(page.getByText("Form reminder draft created. Review recipients and release it from Email.")).toBeVisible();
  await page.goto(campaignUrl);
  await expect(page.getByText("E2E fall travel forms", { exact: true }).first()).toBeVisible();
  await page.getByRole("link", { name: "Record" }).click();
  await page.getByLabel("Pickup contact name").fill("Release Verifier");
  await page.getByLabel("School bus").check();
  await page.getByLabel(/I acknowledge this statement/).check();
  await page.locator('input[type="file"]').setInputFiles(path.resolve("tests/fixtures/library-resource.txt"));
  await page.getByRole("button", { name: "Mark complete" }).click();
  await expect(page.getByText("Response marked complete.")).toBeVisible();
  await expect(page.getByText("complete", { exact: true })).toBeVisible();
  const formResponseDownload = page.waitForEvent("download");
  await page.getByRole("link", { name: "Responses CSV" }).click();
  expect((await formResponseDownload).suggestedFilename()).toBe("band-office-form-responses.csv");
  await page.getByRole("link", { name: "Review" }).click();
  const formFileDownload = page.waitForEvent("download");
  await page.getByRole("link", { name: /library-resource\.txt/ }).click();
  expect((await formFileDownload).suggestedFilename()).toBe("library-resource.txt");
  await page.screenshot({ path: "test-results/e2e-form-response-desktop.png", fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("/forms");
  await expect(page.locator(".mobile-nav").getByRole("link", { name: "Forms" })).toBeVisible();
  await page.screenshot({ path: "test-results/e2e-forms-mobile.png", fullPage: true });
  await page.setViewportSize({ width: 1280, height: 720 });

  await page.goto("/events");
  await expect(page.getByRole("heading", { name: "Events" })).toBeVisible();
  await page.locator("summary").filter({ hasText: "New event" }).click();
  const eventForm = page.locator("form").filter({ hasText: "New event" });
  await eventForm.getByLabel("Event name").fill("E2E fall performance");
  await eventForm.getByLabel("Starts").fill("2026-10-10T17:00");
  await eventForm.getByLabel("Ends").fill("2026-10-10T20:00");
  await eventForm.getByLabel("Location").fill("Release Auditorium");
  await eventForm.getByLabel("Description").fill("Deterministic event workflow acceptance.");
  await eventForm.locator(".segmented-field label").filter({ hasText: "Public" }).click();
  await eventForm.locator(".switch-list label").filter({ hasText: "RSVP" }).click();
  await eventForm.getByLabel(/clarinet/).check();
  await eventForm.getByLabel("Itinerary").fill("4:30 PM Call time\n5:00 PM Warm up\n8:00 PM Dismissal");
  await eventForm.getByRole("button", { name: "Create event" }).click();
  await expect(page.getByText("Event created with a roster snapshot from the selected groups.")).toBeVisible();
  await expect(page.getByRole("heading", { name: "E2E fall performance" })).toBeVisible();
  const eventUrl = new URL(page.url()).pathname;
  await page.getByRole("button", { name: "Publish" }).click();
  await expect(page.getByText("Event status updated.")).toBeVisible();
  const rsvpForm = page.locator("form.compact-update-form").first();
  await rsvpForm.locator("select").selectOption("YES");
  await rsvpForm.getByRole("button", { name: "Save RSVP" }).click();
  await expect(page.getByText("RSVP updated.")).toBeVisible();

  await page.locator("summary").filter({ hasText: "Add item" }).click();
  const eventEquipmentForm = page.locator("form").filter({ hasText: "Add equipment" });
  await eventEquipmentForm.getByLabel("Item").fill("Music stand cart");
  await eventEquipmentForm.getByLabel("Quantity").fill("2");
  await eventEquipmentForm.getByRole("button", { name: "Add equipment" }).click();
  await expect(page.getByText("Equipment item added.")).toBeVisible();
  const packingForm = page.locator("form.packing-form").first();
  await packingForm.locator('input[name="packedQuantity"]').fill("2");
  await packingForm.getByRole("button", { name: /Update packed quantity/ }).click();
  await expect(page.getByText("Packing count updated.")).toBeVisible();

  await page.locator("summary").filter({ hasText: "New opportunity" }).click();
  const volunteerOpportunityForm = page.locator("form").filter({ hasText: "Create opportunity" });
  await volunteerOpportunityForm.getByLabel("Opportunity").fill("Equipment loading");
  await volunteerOpportunityForm.getByLabel("Capacity").fill("1");
  await volunteerOpportunityForm.getByRole("button", { name: "Create opportunity" }).click();
  await expect(page.getByText("Volunteer opportunity created.")).toBeVisible();
  const volunteerForm = page.locator("form").filter({ hasText: "Assign volunteer" });
  await volunteerForm.getByLabel("Assign volunteer").selectOption({ label: "Supporter, Avery" });
  await volunteerForm.getByRole("button", { name: "Assign" }).click();
  await expect(page.getByText("Volunteer assignment recorded.")).toBeVisible();

  await page.locator("summary").filter({ hasText: "Upload" }).click();
  const eventUploadForm = page.locator("form").filter({ hasText: "Store file" });
  await eventUploadForm.getByLabel("Label").fill("E2E itinerary file");
  await eventUploadForm.locator('input[type="file"]').setInputFiles(path.resolve("tests/fixtures/library-resource.txt"));
  await eventUploadForm.getByRole("button", { name: "Store file" }).click();
  await expect(page.getByText("Event file stored in managed local storage.")).toBeVisible();

  await page.locator("summary").filter({ hasText: "Create reminder" }).click();
  const eventReminderForm = page.locator("form").filter({ hasText: "Create reminder" });
  await eventReminderForm.getByLabel("Audience").selectOption("PARTICIPANTS");
  await eventReminderForm.getByRole("button", { name: "Create reminder" }).click();
  await expect(page.getByText("Event reminder created. Review its audience and delivery state in Email.")).toBeVisible();
  await page.goto(`${eventUrl}/attendance`);
  await expect(page.getByRole("heading", { name: "Attendance" })).toBeVisible();
  await page.getByRole("button", { name: "Mark all present" }).click();
  await page.getByRole("button", { name: "Save attendance" }).click();
  await expect(page.getByText("Attendance saved for 1 roster members.")).toBeVisible();
  await page.screenshot({ path: "test-results/e2e-attendance-desktop.png", fullPage: true });
  await page.goto(eventUrl);
  await expect(page.getByText("1/1", { exact: true }).first()).toBeVisible();
  const tripRosterDownload = page.waitForEvent("download");
  await page.getByRole("link", { name: "Trip roster CSV" }).click();
  expect((await tripRosterDownload).suggestedFilename()).toBe("band-office-event-trip-roster.csv");
  const eventFileDownload = page.waitForEvent("download");
  await page.getByRole("link", { name: "Download E2E itinerary file" }).click();
  expect((await eventFileDownload).suggestedFilename()).toBe("library-resource.txt");
  await page.screenshot({ path: "test-results/e2e-event-detail-desktop.png", fullPage: true });
  await page.goto("/events");
  const publicCalendarLink = page.getByRole("link", { name: /Public subscription/ });
  const publicEmbedLink = page.getByRole("link", { name: /Public embed/ });
  await expect(publicCalendarLink).toBeVisible();
  await expect(publicEmbedLink).toBeVisible();
  const publicCalendarPath = await publicCalendarLink.getAttribute("href");
  const publicEmbedPath = await publicEmbedLink.getAttribute("href");
  expect(publicCalendarPath).toBeTruthy();
  expect(publicEmbedPath).toBeTruthy();
  const publicCalendar = await request.get(publicCalendarPath!);
  expect(publicCalendar.status()).toBe(200);
  expect(await publicCalendar.text()).toContain("E2E fall performance");
  const publicEmbed = await request.get(publicEmbedPath!);
  expect(publicEmbed.status()).toBe(200);
  expect(await publicEmbed.text()).toContain("E2E fall performance");
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.locator(".mobile-nav").getByRole("link", { name: "Events" })).toBeVisible();
  await page.screenshot({ path: "test-results/e2e-events-mobile.png", fullPage: true });
  await page.setViewportSize({ width: 1280, height: 720 });
  await page.locator("summary").filter({ hasText: "New private link" }).click();
  const calendarLinkForm = page.locator("form").filter({ hasText: "Create once-only link" });
  await calendarLinkForm.getByLabel("Calendar name").fill("E2E private calendar");
  await calendarLinkForm.getByRole("button", { name: "Create once-only link" }).click();
  await expect(page).toHaveURL((url) => !url.searchParams.has("calendarToken") && !url.searchParams.has("calendarName"));
  const privateCalendarUrl = await page.getByLabel("Private calendar subscription address").inputValue();
  const privateCalendar = await request.get(privateCalendarUrl);
  expect(privateCalendar.status()).toBe(200);
  expect(await privateCalendar.text()).toContain("E2E fall performance");

  await page.goto("/import?kind=assets");
  const assetCsvInput = page.getByLabel("Select assets CSV");
  await expect(assetCsvInput).toBeEnabled();
  await assetCsvInput.setInputFiles(path.resolve("tests/fixtures/import-assets.csv"));
  await expect(page.getByText("1 rows ready for reconciliation")).toBeVisible();
  await page.getByRole("button", { name: "Import assets" }).click();
  await expect(page.getByText("Asset import complete: 1 created, 0 updated.")).toBeVisible();

  await page.goto("/assets");
  await page.getByRole("link", { name: "Print labels" }).click();
  await expect(page.getByRole("heading", { name: "Print asset labels" })).toBeVisible();
  await page.getByLabel("Select RMS-EQP-010").check();
  await expect(page.locator(".label-card.qrcode svg")).toBeVisible();
  await page.screenshot({ path: "test-results/e2e-labels-desktop.png", fullPage: true });
  await page.getByRole("button", { name: "Code 128" }).click();
  await expect(page.locator(".label-card.code128 svg")).toBeVisible();
  await page.evaluate(() => { window.print = () => document.body.setAttribute("data-print-invoked", "true"); });
  await page.getByRole("button", { name: "Print labels" }).click();
  await expect(page.locator("body")).toHaveAttribute("data-print-invoked", "true");
  await page.emulateMedia({ media: "print" });
  await expect(page.locator(".label-controls")).toBeHidden();
  const printSheetWidth = await page.locator(".label-sheet").evaluate((element) => element.getBoundingClientRect().width);
  expect(printSheetWidth).toBeCloseTo(816, 0);
  await page.screenshot({ path: "test-results/e2e-labels-print.png", fullPage: true });
  await page.emulateMedia({ media: "screen" });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: "test-results/e2e-labels-mobile.png", fullPage: true });
  await page.setViewportSize({ width: 1280, height: 720 });
  await page.goto("/assets");
  await page.evaluate(() => {
    class MockBarcodeDetector {
      static async getSupportedFormats() { return ["qr_code", "code_128"]; }
      async detect() { return [{ rawValue: "RMS-EQP-010" }]; }
    }
    Object.defineProperty(window, "BarcodeDetector", { configurable: true, value: MockBarcodeDetector });
    Object.defineProperty(navigator, "mediaDevices", { configurable: true, value: { getUserMedia: async () => new MediaStream() } });
    Object.defineProperty(HTMLMediaElement.prototype, "play", { configurable: true, value: async () => undefined });
  });
  await page.getByRole("button", { name: "Scan inventory" }).click();
  await expect(page.getByRole("dialog", { name: "Scan inventory" })).toBeVisible();
  await page.screenshot({ path: "test-results/e2e-scanner-desktop.png", fullPage: true });
  await page.getByRole("button", { name: "Close scanner" }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole("button", { name: "Scan inventory" }).click();
  await page.screenshot({ path: "test-results/e2e-scanner-mobile.png", fullPage: true });
  await page.getByRole("button", { name: "Close scanner" }).click();
  await page.setViewportSize({ width: 1280, height: 720 });
  await page.getByRole("button", { name: "Scan inventory" }).click();
  await page.getByRole("button", { name: "Use camera" }).click();
  await expect(page).toHaveURL(/\/assets\//);
  await expect(page.getByRole("heading", { name: "RMS-EQP-010" })).toBeVisible();
  await page.getByRole("link", { name: "Print label", exact: true }).click();
  await expect(page).toHaveURL(/\/assets\/labels\?asset=/);
  await expect(page.getByLabel("Select RMS-EQP-010")).toBeChecked();

  await page.goto("/checkout");
  await page.getByRole("textbox", { name: "Person", exact: true }).fill("Release Verifier");
  await page.getByRole("option", { name: /Verifier, Release/ }).click();
  await page.getByLabel("Group context").selectOption({ label: "clarinet" });
  await expect(page.getByLabel("Group context").locator("option:checked")).toHaveText("clarinet");
  await page.getByRole("button", { name: "Scan available asset" }).click();
  await page.getByLabel("Asset tag or barcode").fill("RMS-EQP-010");
  await page.getByRole("button", { name: "Find asset" }).click();
  await expect(page.getByRole("textbox", { name: "Asset", exact: true })).toHaveValue(/RMS-EQP-010/);
  await page.getByLabel("Expected return").fill("2026-08-15");
  await page.getByRole("button", { name: "Complete checkout" }).click();
  await expect(page).toHaveURL(/\/agreements\//);
  await expect(page.getByText("Checkout saved")).toBeVisible();
  await expect(page.getByRole("heading", { name: "Ridgeline Middle School Band" })).toBeVisible();
  await expect(page.getByText(/Grade 7 · clarinet/)).toBeVisible();

  await page.goto("/checkin");
  await page.getByRole("button", { name: "Scan assigned asset" }).click();
  await page.getByLabel("Asset tag or barcode").fill("RMS-EQP-010");
  await page.getByRole("button", { name: "Find asset" }).click();
  await expect(page.getByRole("textbox", { name: "Current assignment", exact: true })).toHaveValue(/RMS-EQP-010/);
  await page.getByLabel(/Open a repair for damage/).check();
  await page.getByLabel("Repair description").fill("Bent frame found during automated return test");
  await page.getByRole("button", { name: "Complete check-in" }).click();
  await expect(page.getByText("Check-in recorded and asset status updated.")).toBeVisible();
  await page.goto("/repairs");
  await expect(page.getByText("Bent frame found during automated return test")).toBeVisible();

  await page.goto("/roster");
  await page.locator("summary").filter({ hasText: "Add person" }).click();
  const helperPersonForm = page.locator("form").filter({ hasText: "New person" });
  await helperPersonForm.locator('input[name="firstName"]').fill("Inventory");
  await helperPersonForm.locator('input[name="lastName"]').fill("Helper");
  await helperPersonForm.locator('input[name="classifications"][value="STUDENT"]').uncheck();
  await helperPersonForm.locator('input[name="classifications"][value="STAFF"]').check();
  await helperPersonForm.getByRole("button", { name: "Add person" }).click();

  await page.goto("/settings");
  const helperAccountForm = page.locator("form").filter({ hasText: "Create staff account" });
  await helperAccountForm.getByLabel("Staff person").selectOption({ label: "Helper, Inventory" });
  await helperAccountForm.getByLabel("Username").fill("inventory-helper-e2e");
  await helperAccountForm.getByLabel("Temporary password").fill("BandOffice-Helper-Password!");
  await helperAccountForm.getByLabel("Role").selectOption("INVENTORY_HELPER");
  await helperAccountForm.getByRole("button", { name: "Create staff account" }).click();
  await expect(page.getByText("Staff account created.")).toBeVisible();
  await page.getByLabel("Backup passphrase").fill("BandOffice-E2E-Backup-Key!");
  const downloadPromise = page.waitForEvent("download");
  await page.getByRole("button", { name: "Encrypted backup" }).click();
  const download = await downloadPromise;
  expect(download.suggestedFilename()).toMatch(/^band-office-backup-\d{4}-\d{2}-\d{2}\.bandoffice$/);
  const backupPath = await download.path();
  expect(backupPath).toBeTruthy();
  expect((await readFile(backupPath!)).subarray(0, 10).toString()).toBe("BANDOSENC1");
  const savedBackupPath = path.resolve("test-results/e2e-backup.bandoffice");
  await download.saveAs(savedBackupPath);
  const verification = await execFileAsync(process.execPath, ["scripts/verify-backup.mjs", savedBackupPath, "BandOffice-E2E-Backup-Key!"]);
  expect(verification.stdout).toContain("SQLite integrity and foreign keys ok, 51 CSV table counts match");

  await page.screenshot({ path: "test-results/e2e-settings-desktop.png", fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("/today");
  await expect(page.locator(".mobile-bar")).toBeVisible();
  await expect(page.locator(".sidebar")).toBeHidden();
  await expect(page.getByRole("heading", { name: "Today" })).toBeVisible();
  await page.screenshot({ path: "test-results/e2e-today-mobile.png", fullPage: true });

  await page.getByRole("button", { name: "Sign out" }).click();
  await expect(page).toHaveURL(/\/login/);
  const response = await request.get("/api/export/who-has-what");
  expect(response.status()).toBe(401);

  await page.getByLabel("Username").fill("inventory-helper-e2e");
  await page.getByLabel("Password").fill("BandOffice-Helper-Password!");
  await page.getByRole("button", { name: "Sign in" }).click();
  await expect(page).toHaveURL(/\/today/);
  await expect(page.getByRole("heading", { name: "Upcoming events" })).toHaveCount(0);
  await expect(page.getByRole("link", { name: "Events" })).toHaveCount(0);
  await expect(page.getByRole("link", { name: "Email" })).toHaveCount(0);
  await expect(page.getByRole("link", { name: "People" })).toBeVisible();
  await expect(page.getByRole("link", { name: "Assets" })).toBeVisible();
  await page.goto("/roster");
  await expect(page.getByText("avery.supporter@example.test")).toHaveCount(0);
  await page.getByRole("link", { name: /Verifier, Release/ }).click();
  await expect(page.getByRole("heading", { name: "Family links" })).toHaveCount(0);
  await expect(page.getByText("Email", { exact: true })).toHaveCount(0);
  expect((await page.request.get("/api/forms/files/not-available")).status()).toBe(403);
  expect((await page.request.get("/api/events/files/not-available")).status()).toBe(403);
  await page.goto("/events");
  await expect(page).toHaveURL(/\/today\?error=/);
  await expect(page.getByText("Events access is not available for this account.")).toBeVisible();
  await page.getByRole("button", { name: "Sign out" }).click();
});
