import Link from "next/link";
import { ArrowDown, ArrowLeft, ArrowUp, CheckCircle2, CopyPlus, FileInput, Plus, Send, Trash2 } from "lucide-react";
import { notFound, redirect } from "next/navigation";
import { addFormQuestionAction, createFormCampaignAction, createFormRevisionAction, moveFormQuestionAction, publishFormVersionAction, removeFormQuestionAction, updateDraftFormVersionAction } from "@/app/forms-actions";
import { Field } from "@/components/field";
import { FlashMessage } from "@/components/flash-message";
import { PageHeader } from "@/components/page-header";
import { StatusPill } from "@/components/status-pill";
import { SubmitButton } from "@/components/submit-button";
import { FormAudienceType, FormQuestionType, FormRecipientMode, FormTemplateVersionStatus } from "@/generated/prisma/client";
import { hasPermission, requireUser } from "@/lib/auth";
import { getDb } from "@/lib/db";
import { formatDate, titleCase } from "@/lib/format";

export const dynamic = "force-dynamic";

function options(question: { optionsJson: string | null }) {
  try { return question.optionsJson ? JSON.parse(question.optionsJson) as string[] : []; } catch { return []; }
}

export default async function FormTemplatePage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ success?: string; error?: string }> }) {
  const [{ id }, query, user] = await Promise.all([params, searchParams, requireUser()]);
  if (!hasPermission(user, "VIEW_FORMS")) redirect("/today");
  const db = getDb();
  const [template, groups, students] = await Promise.all([
    db.formTemplate.findFirst({ where: { id, programId: user.programId }, include: { versions: { include: { questions: { orderBy: { position: "asc" } }, _count: { select: { campaigns: true } } }, orderBy: { version: "desc" } } } }),
    db.group.findMany({ where: { programId: user.programId, active: true }, orderBy: [{ kind: "asc" }, { name: "asc" }] }),
    db.person.findMany({ where: { programId: user.programId, status: "ACTIVE", classifications: { some: { classification: "STUDENT" } } }, include: { studentProfile: true }, orderBy: [{ lastName: "asc" }, { firstName: "asc" }] }),
  ]);
  if (!template) notFound();
  const draft = template.versions.find((version) => version.status === FormTemplateVersionStatus.DRAFT);
  const published = template.versions.find((version) => version.status === FormTemplateVersionStatus.PUBLISHED);
  const displayed = draft ?? published ?? template.versions[0];
  if (!displayed) notFound();
  const canManage = hasPermission(user, "MANAGE_FORMS");
  const today = new Date().toISOString().slice(0, 10);

  return <main className="content">
    <Link className="back-link" href="/forms"><ArrowLeft size={16} />Forms</Link>
    <PageHeader eyebrow={`Version ${displayed.version} · ${titleCase(displayed.status)}`} title={template.name} description={template.description ?? displayed.title} icon={FileInput} actions={<><StatusPill value={displayed.status} />{canManage && !draft ? <form action={createFormRevisionAction}><input type="hidden" name="templateId" value={template.id} /><button className="button secondary" type="submit"><CopyPlus size={16} />Create revision</button></form> : null}</>} />
    <FlashMessage {...query} />
    <section className="asset-summary-band form-summary-band"><div><span>Form title</span><strong>{displayed.title}</strong></div><div><span>Questions</span><strong>{displayed.questions.length}</strong></div><div><span>Retention</span><strong>{displayed.retentionDays ? `${displayed.retentionDays} days` : "Manual"}</strong></div><div><span>Published</span><strong>{formatDate(published?.publishedAt)}</strong></div><div><span>Campaigns</span><strong>{template.versions.reduce((sum, version) => sum + version._count.campaigns, 0)}</strong></div></section>

    <div className="detail-grid form-builder-grid">
      <section className="detail-main">
        {draft && canManage ? <form action={updateDraftFormVersionAction} className="work-panel form-grid"><input type="hidden" name="templateId" value={template.id} /><input type="hidden" name="versionId" value={draft.id} /><div className="section-heading field-wide"><div><h2>Draft details</h2><p>Published versions remain unchanged for existing requests</p></div></div><Field label="Template name"><input name="name" defaultValue={template.name} required /></Field><Field label="Form title"><input name="title" defaultValue={draft.title} required /></Field><Field label="Description" wide><textarea name="description" rows={2} defaultValue={template.description ?? ""} /></Field><Field label="Instructions" wide><textarea name="instructions" rows={4} defaultValue={draft.instructions ?? ""} /></Field><Field label="Retention days" wide hint="Blank means manual retention. Purging removes answers and uploads but retains completion history."><input name="retentionDays" type="number" min="1" max="3650" defaultValue={draft.retentionDays ?? ""} /></Field><div className="form-actions field-wide"><SubmitButton>Save draft details</SubmitButton></div></form> : <section className="work-panel"><div className="section-heading"><div><h2>{displayed.title}</h2><p>{displayed.instructions || "No instructions entered."}</p></div></div></section>}

        <div className="section-heading top-gap"><div><h2>Questions</h2><p>Version {displayed.version} question order</p></div>{draft && canManage ? <details className="popover wide"><summary className="button primary"><Plus size={16} />Add question</summary><form action={addFormQuestionAction} className="popover-panel form-grid"><input type="hidden" name="templateId" value={template.id} /><input type="hidden" name="versionId" value={draft.id} /><h3>Add question</h3><Field label="Prompt" wide><textarea name="prompt" rows={2} required /></Field><Field label="Type"><select name="type" defaultValue={FormQuestionType.SHORT_TEXT}>{Object.values(FormQuestionType).map((value) => <option value={value} key={value}>{titleCase(value)}</option>)}</select></Field><Field label="Help text"><input name="helpText" /></Field><Field label="Choice options" wide hint="For single- or multiple-choice questions, enter one option per line."><textarea name="options" rows={5} /></Field><label className="check-row field-wide"><input name="required" type="checkbox" /><span>Response required before completion</span></label><div className="form-actions field-wide"><SubmitButton>Add question</SubmitButton></div></form></details> : null}</div>
        <div className="form-question-list">{displayed.questions.map((question, index) => <article key={question.id} className="form-question-card"><span className="question-number">{question.position}</span><div className="question-copy"><div><strong>{question.prompt}</strong>{question.required ? <span className="required-marker">Required</span> : null}</div><small>{titleCase(question.type)}{question.helpText ? ` · ${question.helpText}` : ""}</small>{options(question).length ? <div className="choice-preview">{options(question).map((option) => <span key={option}>{option}</span>)}</div> : null}</div>{draft && canManage ? <div className="question-actions"><form action={moveFormQuestionAction}><input type="hidden" name="templateId" value={template.id} /><input type="hidden" name="questionId" value={question.id} /><input type="hidden" name="direction" value="up" /><button className="icon-button" type="submit" disabled={index === 0} aria-label="Move question up" title="Move up"><ArrowUp size={15} /></button></form><form action={moveFormQuestionAction}><input type="hidden" name="templateId" value={template.id} /><input type="hidden" name="questionId" value={question.id} /><input type="hidden" name="direction" value="down" /><button className="icon-button" type="submit" disabled={index === displayed.questions.length - 1} aria-label="Move question down" title="Move down"><ArrowDown size={15} /></button></form><form action={removeFormQuestionAction}><input type="hidden" name="templateId" value={template.id} /><input type="hidden" name="questionId" value={question.id} /><button className="icon-button danger-icon" type="submit" aria-label="Remove question" title="Remove question"><Trash2 size={15} /></button></form></div> : null}</article>)}{displayed.questions.length === 0 ? <div className="empty-state"><FileInput size={24} /><strong>No questions yet</strong><span>Add the information this form must collect.</span></div> : null}</div>

        {draft && canManage ? <section className="publish-band"><CheckCircle2 size={22} /><div><strong>Publish version {draft.version}</strong><span>Publishing locks this exact wording and question order for recipient history.</span></div><form action={publishFormVersionAction}><input type="hidden" name="templateId" value={template.id} /><input type="hidden" name="versionId" value={draft.id} /><button className="button primary" type="submit">Publish form</button></form></section> : null}
      </section>

      <aside className="detail-aside form-builder-aside"><h3>Versions</h3><div className="version-list">{template.versions.map((version) => <div key={version.id}><span><strong>Version {version.version}</strong><small>{version.questions.length} questions · {version._count.campaigns} campaigns</small></span><StatusPill value={version.status} /></div>)}</div>{published && canManage ? <details className="popover campaign-popover"><summary className="button primary full-width"><Send size={16} />Create request campaign</summary><form action={createFormCampaignAction} className="popover-panel form-grid"><input type="hidden" name="templateId" value={template.id} /><input type="hidden" name="versionId" value={published.id} /><h3>Assign {published.title}</h3><Field label="Campaign name" wide><input name="name" required defaultValue={`${published.title} · ${today}`} /></Field><Field label="Due date"><input name="dueAt" type="date" /></Field><Field label="Recipients"><select name="recipientMode" defaultValue={FormRecipientMode.GUARDIANS}>{Object.values(FormRecipientMode).map((value) => <option key={value} value={value}>{titleCase(value)}</option>)}</select></Field><Field label="Audience source" wide><select name="audienceType" defaultValue={FormAudienceType.ACTIVE_STUDENTS}><option value={FormAudienceType.ACTIVE_STUDENTS}>All active students</option><option value={FormAudienceType.GROUP}>One group</option><option value={FormAudienceType.GRADE}>One grade</option><option value={FormAudienceType.PERSON}>One student</option></select></Field><Field label="Group"><select name="groupId" defaultValue=""><option value="">Choose when using one group</option>{groups.map((group) => <option key={group.id} value={group.id}>{group.name}</option>)}</select></Field><Field label="Grade"><select name="grade" defaultValue=""><option value="">Choose when using one grade</option>{[5, 6, 7, 8, 9, 10, 11, 12].map((grade) => <option key={grade} value={grade}>Grade {grade}</option>)}</select></Field><Field label="Student" wide><select name="personId" defaultValue=""><option value="">Choose when using one student</option>{students.map((student) => <option key={student.id} value={student.id}>{student.lastName}, {student.firstName}{student.studentProfile ? ` · grade ${student.studentProfile.grade}` : ""}</option>)}</select></Field><div className="form-actions field-wide"><SubmitButton>Create recipient requests</SubmitButton></div></form></details> : null}<div className="form-policy-note"><strong>No eSignature</strong><p>Acknowledgment questions record an ordinary checked response and timestamp. They are not represented as legal signatures.</p></div></aside>
    </div>
  </main>;
}
